name: Bsides montreal 2023

on: workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
      - run: |
            id
            uname -a
            env
            echo "hello world montreal"
  security:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the owasp zap
    permissions: write-all
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com/'
